Implement method convert_queue_status for torque
pyiron/pysqa pull request #157
Opened 2023-04-17 22:28 UTC by ligerzero-ai

Implements queue_table functionality for torque for remote submission purposes

2023-04-18 01:47 UTC, jan-janssen requested changes
@ligerzero-ai can you add a test for the `convert_queue_status()` function? Just provide a set of example inputs and check they are parsed correctly.

2023-04-18 16:14 UTC, jan-janssen commented on pysqa/wrapper/torque.py
> +import subprocess
```suggestion
```

2023-04-19 06:19 UTC, ligerzero-ai commented
> @ligerzero-ai can you add a test for the `convert_queue_status()` function? Just provide a set of example inputs and check they are parsed correctly.

Should be done now

2023-04-19 06:20 UTC, ligerzero-ai commented
Slurm is missing tests, actually. There is only a test for SGE as far as I can tell. We should add it at some point - I'll open an issue as a reminder

2023-04-19 13:55 UTC, jan-janssen approved these changes
Looks good to me

2023-04-19 15:17 UTC, jan-janssen commented on pysqa/wrapper/torque.py
> +        job_id_lst = [job_id_str.split(sep=".")[0] for job_id_str in job_id_lst]
```suggestion
       job_id_lst = [int(job_id_str.split(sep=".")[0]) for job_id_str in job_id_lst]
```

2023-04-19 15:17 UTC, jan-janssen commented on pysqa/wrapper/torque.py
> +        job_id_lst = [job_id_str.split(sep=".")[0] for job_id_str in job_id_lst]
Queue IDs should be integer

2023-04-19 16:06 UTC, merged